In [1]:
%run Zeidel.ipynb
%run Gauss.ipynb
%run Jacobi.ipynb
%run Gradient.ipynb

In [2]:
def _format_matrix(min, max, size):
    return np.array((max - min) * np.random.random((size, size)) + min, dtype=np.float64)
    
def rand_matrix(size):
    A = np.array(np.random.rand(size, size), dtype=np.float64)
    A = np.tril(A) + np.tril(A, -1).T
    return A.T * A

def diag_matrix(size):
    A = _format_matrix(0.0, 10.0, size)
    for i in range(size):
        A[i, i] = sum(A[i]) + 1
    return A

def hilbert_matrix(size):
    ans = np.array(np.zeros((size, size)), dtype=np.float64)
    for i in range(size):
        for j in range(size):
            ans[i, j] = 1.0 / (i + j + 1)
    return ans

def gen_right_column(size):
    return np.array(np.random.random(size), dtype=np.float64)

In [3]:
def equalVector(a, b, eps):
    return math.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])) < eps

In [4]:
def _test(method, matrix, column):
    return method(matrix, column)

def _check_eps(a, b, eps):
    return abs(a - b) < eps
EPSILON = 1e-6
def _check_ans(matrix, column, res, size):
    eps = EPSILON
    c = np.matmul(matrix, res)
    for i in range(size):
        if not _check_eps(c[i], column[i], eps):
            return False
    return True

def _testAll(matrix_gen, size, methods):
    matrix, column = matrix_gen(size), gen_right_column(size)
    print(f'Тест для матрицы\n {matrix} и столбца {column}')
    for method in methods:
        print(f'Результат выполнения метода {method.__name__}:')
        res = _test(method, matrix, column)
        check = _check_ans(matrix, column, res, size)
        if check:
            print(f'{res}. Погрешность не больше {EPSILON}\n')
        else:
            print(f'разошлось: matrix * res = {np.matmul(matrix, res)}\n ожидаемый столбец = {column}\n')

def _get_methods():
    return [zeidelMethod, zeidelMethodRelax, gaussMethod, jacobiMethod, gradient_descent]

def testDiagMatrix(size):
    _testAll(diag_matrix, size, _get_methods())

def testHilbertMatrix(size):
    _testAll(hilbert_matrix, size, _get_methods())
    
def testRandMatrix(size):
    _testAll(rand_matrix, size, _get_methods())

In [5]:
testDiagMatrix(10)

Тест для матрицы
 [[4.69136910e+01 6.18925549e+00 9.21516724e-01 3.99573548e+00
  1.07194767e+00 7.69690838e+00 6.94203300e+00 4.53593642e+00
  8.03258393e+00 4.18452352e+00]
 [2.92124554e-01 4.65188853e+01 4.39541161e+00 7.30963525e+00
  5.51735540e+00 3.92893391e+00 2.37133871e+00 1.88536513e+00
  8.48653196e+00 9.85235683e+00]
 [2.20950959e+00 3.09076636e+00 5.00466522e+01 5.11045546e+00
  9.84729280e+00 6.87977456e+00 4.00945924e+00 5.69169848e+00
  2.16026544e+00 7.12461401e+00]
 [2.38427038e+00 5.52277269e+00 9.63879093e+00 5.37963681e+01
  8.42693870e+00 5.68445403e-01 2.48747666e+00 6.35365802e+00
  6.83486499e+00 7.69917775e+00]
 [3.57181309e+00 2.19372979e-01 3.18634557e+00 6.14578464e+00
  3.72592524e+01 1.60187297e+00 3.21150855e+00 7.66411287e+00
  4.72423016e+00 5.23011272e-01]
 [1.86986615e+00 2.14534207e+00 5.38574360e+00 6.13261951e+00
  6.38751678e+00 4.60673691e+01 9.58539028e-01 9.98322499e+00
  1.25796206e-01 6.07948522e+00]
 [2.32898315e+00 3.70031402e+00 7.982247

In [6]:
testRandMatrix(10)

Тест для матрицы
 [[0.95769956 0.46373738 0.00631929 0.13750606 0.24798132 0.03803542
  0.65156118 0.21665775 0.01670728 0.0032212 ]
 [0.46373738 0.56060333 0.0204264  0.91783914 0.31269304 0.61029176
  0.99544812 0.05808809 0.26787177 0.05576702]
 [0.00631929 0.0204264  0.13269437 0.19525473 0.03209738 0.39315904
  0.17275552 0.02891318 0.96870776 0.94051368]
 [0.13750606 0.91783914 0.19525473 0.42058867 0.02573311 0.57480595
  0.8760301  0.03626765 0.50031524 0.06910467]
 [0.24798132 0.31269304 0.03209738 0.02573311 0.51654059 0.22945921
  0.29007989 0.13606188 0.6703218  0.58580223]
 [0.03803542 0.61029176 0.39315904 0.57480595 0.22945921 0.59533328
  0.21248486 0.04538702 0.04756289 0.59673259]
 [0.65156118 0.99544812 0.17275552 0.8760301  0.29007989 0.21248486
  0.33367382 0.84455063 0.52318563 0.0260755 ]
 [0.21665775 0.05808809 0.02891318 0.03626765 0.13606188 0.04538702
  0.84455063 0.33274967 0.22953725 0.95058504]
 [0.01670728 0.26787177 0.96870776 0.50031524 0.6703218  0.047

/home/kranya/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/home/kranya/.local/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
/home/kranya/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/kranya/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/kranya/.local/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


In [7]:
testHilbertMatrix(5)

Тест для матрицы
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] и столбца [0.28178598 0.24793677 0.01790702 0.68644057 0.1257662 ]
Результат выполнения метода zeidelMethod:
Iterations =  601057
[-930.318096041813, 17633.986304902865, -76563.13739757444, 116081.74497050137, -56928.91856929539]. Погрешность не больше 1e-06

Результат выполнения метода zeidelMethodRelax:
Iterations =  153327
2000000
[-930.3180960487527, 17633.986305032675, -76563.1373981343, 116081.7449713469, -56928.918569709]. Погрешность не больше 1e-06

Результат выполнения метода gaussMethod:
[-930.3180960515687, 17633.98630508191, -76563.13739833736, 116081.74497164396, -56928.9185698509]. Погрешность не больше 1e-06

Результат выполнения метода jacobiMethod:
Iterations =  2
