In [36]:
%run Zeidel.ipynb
%run Gauss.ipynb

In [37]:
def _format_matrix(min, max, size):
    return np.array((max - min) * np.random.random((size, size)) + min, dtype=np.float64)
    
def rand_matrix(size):
    A = np.array(np.random.rand(size, size), dtype=np.float64)
    A = np.tril(A) + np.tril(A, -1).T
    return A.T * A

def diag_matrix(size):
    A = _format_matrix(0.0, 10.0, size)
    for i in range(size):
        A[i, i] = sum(A[i]) + 1
    return A

def hilbert_matrix(size):
    ans = np.array(np.zeros((size, size)), dtype=np.float64)
    for i in range(size):
        for j in range(size):
            ans[i, j] = 1.0 / (i + j + 1)
    return ans

def gen_right_column(size):
    return np.array(np.random.random(size), dtype=np.float64)

In [38]:
def equalVector(a, b, eps):
    return math.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])) < eps

In [39]:
def _test(method, matrix, column):
    return method(matrix, column)

def _check_eps(a, b, eps):
    return abs(a - b) < eps
EPSILON = 1e-2
def _check_ans(matrix, column, res, size):
    eps = EPSILON
    c = np.matmul(matrix, res)
    for i in range(size):
        if not _check_eps(c[i], column[i], eps):
            return False
    return True

def _testAll(matrix_gen, size, methods):
    matrix, column = matrix_gen(size), gen_right_column(size)
    print(f'Тест для матрицы {matrix} и столбца {column}')
    for method in methods:
        print(f'Результат выполнения метода {method.__name__}:')
        res = _test(method, matrix, column)
        check = _check_ans(matrix, column, res, size)
        if check:
            print(f'{res}. Погрешность не больше {EPSILON}\n')
        else:
            print(f'разошлось: matrix * res = {np.matmul(matrix, res)}\n ожидаемый столбец = {column}\n')

def _get_methods():
    return [zeidelMethod, zeidelMethodRelax, gaussingMethod]

def testDiagMatrix(size):
    _testAll(diag_matrix, size, _get_methods())

def testHilbertMatrix(size):
    _testAll(hilbert_matrix, size, _get_methods())
    
def testRandMatrix(size):
    _testAll(rand_matrix, size, _get_methods())

In [40]:
testDiagMatrix(10)

Тест для матрицы [[49.62051278  6.37920628  7.94135629  8.20663429  7.25351361  1.15376174
   6.35659788  2.01155147  6.73506084  1.74140837]
 [ 2.91654423 57.37521669  4.94971986  5.38479283  8.79239306  0.73593319
   7.58284151  3.93950015  8.63970046  5.00287984]
 [ 6.39044464  6.91121499 54.18488155  2.32583895  2.29822652  9.37273764
   4.03757694  4.92219779  2.08148541  9.05283424]
 [ 7.81622725  3.07081668  1.69472118 55.39268048  5.4620303   6.49936587
   1.74019628  5.32396052  8.03876072  6.54042321]
 [ 1.18602297  4.68950491  3.64160092  8.40036226 51.59984688  8.45315777
   9.46201911  4.24022793  2.49042538  7.38301957]
 [ 6.73156444  5.75595633  4.91683899  0.43420792  5.67366333 48.55640415
   1.54166695  6.56998833  3.12111303  3.78623618]
 [ 8.14946219  0.15888723  8.40176317  3.18861887  3.98443658  9.73752925
  48.3221675   1.40842002  1.46619416  7.49430688]
 [ 3.28544673  7.03762084  5.7446426   1.74559747  6.88463981  4.12145743
   6.50647205 49.09939392  4.25781

In [41]:
testRandMatrix(4)

Тест для матрицы [[9.32242167e-01 3.98450744e-01 2.51387243e-04 1.69974155e-01]
 [3.98450744e-01 8.37199326e-01 4.22168768e-01 5.03225214e-01]
 [2.51387243e-04 4.22168768e-01 3.66110820e-01 3.12661201e-01]
 [1.69974155e-01 5.03225214e-01 3.12661201e-01 2.62408306e-01]] и столбца [0.82709129 0.29408558 0.82421882 0.55337291]
Результат выполнения метода zeidelMethod:


/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.82709129 0.29408558 0.82421882 0.55337291]

Результат выполнения метода zeidelMethodRelax:


/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in double_scalars
  


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.82709129 0.29408558 0.82421882 0.55337291]

Результат выполнения метода gaussingMethod:
[3.3002997800412364, -5.028403608827073, 9.295163869363819, -1.4611213225103612]. Погрешность не больше 0.01



In [42]:
testHilbertMatrix(5)

Тест для матрицы [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] и столбца [0.01420577 0.2474189  0.47309505 0.34956118 0.6963851 ]
Результат выполнения метода zeidelMethod:
Iterations =  200000
[372.130382441376, -7134.819170114721, 31262.909896308247, -47774.99575559852, 23590.36189105972]. Погрешность не больше 0.01

Результат выполнения метода zeidelMethodRelax:
Iterations =  105534
[372.21623615350126, -7136.395175154519, 31269.624243702037, -47785.048198077086, 23595.247627376157]. Погрешность не больше 0.01

Результат выполнения метода gaussingMethod:
[372.2162403080016, -7136.395247362113, 31269.624540441127, -47785.04863099203, 23595.247833703455]. Погрешность не больше 0.01

