In [1]:
%run Zeidel.ipynb
%run Gauss.ipynb
%run Jacobi.ipynb
%run Gradient.ipynb

In [2]:
def _format_matrix(min, max, size):
    return np.array((max - min) * np.random.random((size, size)) + min, dtype=np.float64)
    
def rand_matrix(size):
    A = np.array(np.random.rand(size, size), dtype=np.float64)
    A = np.tril(A) + np.tril(A, -1).T
    return A.T * A

def diag_matrix(size):
    A = _format_matrix(0.0, 10.0, size)
    for i in range(size):
        A[i, i] = sum(A[i]) + 1
    return A

def hilbert_matrix(size):
    ans = np.array(np.zeros((size, size)), dtype=np.float64)
    for i in range(size):
        for j in range(size):
            ans[i, j] = 1.0 / (i + j + 1)
    return ans

def gen_right_column(size):
    return np.array(np.random.random(size), dtype=np.float64)

In [3]:
def equalVector(a, b, eps):
    return math.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])) < eps

In [4]:
def _test(method, matrix, column):
    return method(matrix, column)

def _check_eps(a, b, eps):
    return abs(a - b) < eps
EPSILON = 1e-2
def _check_ans(matrix, column, res, size):
    eps = EPSILON
    c = np.matmul(matrix, res)
    for i in range(size):
        if not _check_eps(c[i], column[i], eps):
            return False
    return True

def _testAll(matrix_gen, size, methods):
    matrix, column = matrix_gen(size), gen_right_column(size)
    print(f'Тест для матрицы\n {matrix} и столбца {column}')
    for method in methods:
        print(f'Результат выполнения метода {method.__name__}:')
        res = _test(method, matrix, column)
        check = _check_ans(matrix, column, res, size)
        if check:
            print(f'{res}. Погрешность не больше {EPSILON}\n')
        else:
            print(f'разошлось: matrix * res = {np.matmul(matrix, res)}\n ожидаемый столбец = {column}\n')

def _get_methods():
    return [zeidelMethod, zeidelMethodRelax, gaussMethod, jacobiMethod, gradient_descent]

def testDiagMatrix(size):
    _testAll(diag_matrix, size, _get_methods())

def testHilbertMatrix(size):
    _testAll(hilbert_matrix, size, _get_methods())
    
def testRandMatrix(size):
    _testAll(rand_matrix, size, _get_methods())

In [5]:
testDiagMatrix(10)

Тест для матрицы
 [[59.64282569  5.92934561  9.8930969   3.46038847  7.78022105  0.333608
   0.59623832  7.68766552  5.62008967  7.42230231]
 [ 5.61636161 36.16475248  0.14719735  0.90709687  0.22214902  6.45525899
   0.56772238  7.71619584  7.05599262  4.14417485]
 [ 5.75354959  6.41096133 63.71659634  0.76824157  7.96834264  7.48689966
   2.39008705  6.06110613  8.75170886  8.04757864]
 [ 3.64528876  6.75464411  9.73533607 64.96161534  7.12911019  8.04370909
   8.89304011  7.80658789  0.54122488  5.72395181]
 [ 0.17361532  5.49361704  0.50650932  8.05606338 47.10844444  6.02837075
   0.50833625  3.32935239  7.07000797  7.08560667]
 [ 0.57195236  0.80703914  5.8086067   7.07416962  7.90178689 45.34301813
   5.34390249  6.05931163  6.38028888  3.41740139]
 [ 8.02768067  4.42589495  9.92060619  7.77811567  3.62506787  1.07218266
  53.73898266  2.91225139  3.12851012  8.36463443]
 [ 7.77920312  3.92838697  5.25915444  9.06415308  8.81033681  2.29379668
   0.50042402 52.96915338  8.789790

In [6]:
testRandMatrix(4)

Тест для матрицы
 [[0.54184988 0.23413416 0.56069354 0.12100285]
 [0.23413416 0.52654714 0.04884017 0.10880507]
 [0.56069354 0.04884017 0.09546685 0.91151008]
 [0.12100285 0.10880507 0.91151008 0.18229606]] и столбца [0.67932551 0.03367049 0.88218544 0.75769151]
Результат выполнения метода zeidelMethod:


c:\users\pwx779030\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
c:\users\pwx779030\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
c:\users\pwx779030\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.67932551 0.03367049 0.88218544 0.75769151]

Результат выполнения метода zeidelMethodRelax:


c:\users\pwx779030\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
c:\users\pwx779030\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.67932551 0.03367049 0.88218544 0.75769151]

Результат выполнения метода gaussMethod:
[0.579000693978358, -0.3728877389144957, 0.6869605801562474, 0.5597013556423984]. Погрешность не больше 0.01

Результат выполнения метода jacobiMethod:
Iterations =  2
[ 0.57900069 -0.37288774  0.68696058  0.55970136]. Погрешность не больше 0.01

Результат выполнения метода gradient_descent:
Iterations: 4
[ 0.57900069 -0.37288774  0.68696058  0.55970136]. Погрешность не больше 0.01



In [7]:
testHilbertMatrix(5)

Тест для матрицы
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] и столбца [0.93666703 0.59722644 0.84898123 0.87788062 0.39990342]
Результат выполнения метода zeidelMethod:
Iterations =  200000
[-241.34838575927338, 5097.37262677894, -23471.001898746683, 36938.88386215707, -18587.274618740412]. Погрешность не больше 0.01

Результат выполнения метода zeidelMethodRelax:
Iterations =  104214
[-241.41467803200283, 5098.589546031377, -23476.186414222153, 36946.64590631248, -18591.047165605283]. Погрешность не больше 0.01

Результат выполнения метода gaussMethod:
[-241.4146821859778, 5098.589618230275, -23476.186710926417, 36946.64633917741, -18591.047371909]. Погрешность не больше 0.01

Результат выполнения метода jacobiMethod:
Iterations =  2
[  -24