In [23]:
%run Zeidel.ipynb
%run Gauss.ipynb
%run Jacobi.ipynb

In [24]:
def _format_matrix(min, max, size):
    return np.array((max - min) * np.random.random((size, size)) + min, dtype=np.float64)
    
def rand_matrix(size):
    A = np.array(np.random.rand(size, size), dtype=np.float64)
    A = np.tril(A) + np.tril(A, -1).T
    return A.T * A

def diag_matrix(size):
    A = _format_matrix(0.0, 10.0, size)
    for i in range(size):
        A[i, i] = sum(A[i]) + 1
    return A

def hilbert_matrix(size):
    ans = np.array(np.zeros((size, size)), dtype=np.float64)
    for i in range(size):
        for j in range(size):
            ans[i, j] = 1.0 / (i + j + 1)
    return ans

def gen_right_column(size):
    return np.array(np.random.random(size), dtype=np.float64)

In [25]:
def equalVector(a, b, eps):
    return math.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])) < eps

In [30]:
def _test(method, matrix, column):
    return method(matrix, column)

def _check_eps(a, b, eps):
    return abs(a - b) < eps
EPSILON = 1e-2
def _check_ans(matrix, column, res, size):
    eps = EPSILON
    c = np.matmul(matrix, res)
    for i in range(size):
        if not _check_eps(c[i], column[i], eps):
            return False
    return True

def _testAll(matrix_gen, size, methods):
    matrix, column = matrix_gen(size), gen_right_column(size)
    print(f'Тест для матрицы\n {matrix} и столбца {column}')
    for method in methods:
        print(f'Результат выполнения метода {method.__name__}:')
        res = _test(method, matrix, column)
        check = _check_ans(matrix, column, res, size)
        if check:
            print(f'{res}. Погрешность не больше {EPSILON}\n')
        else:
            print(f'разошлось: matrix * res = {np.matmul(matrix, res)}\n ожидаемый столбец = {column}\n')

def _get_methods():
    return [zeidelMethod, zeidelMethodRelax, gaussMethod, jacobiMethod]

def testDiagMatrix(size):
    _testAll(diag_matrix, size, _get_methods())

def testHilbertMatrix(size):
    _testAll(hilbert_matrix, size, _get_methods())
    
def testRandMatrix(size):
    _testAll(rand_matrix, size, _get_methods())

In [31]:
testDiagMatrix(10)

Тест для матрицы
 [[50.04201494  4.66600045  6.20961182  7.73972617  6.44410281  4.09149717
   0.58334999  5.30089796  5.1285406   3.04409021]
 [ 4.42515375 51.11908455  9.33873067  7.4045979   7.0492499   2.08027972
   7.00056331  5.7613922   4.55756445  0.96143738]
 [ 0.16450679  9.48180377 49.6839594   0.58437251  8.45210552  8.24086039
   9.62349034  1.67122678  6.86043469  2.7395134 ]
 [ 0.29059843  2.38550759  5.1757659  35.31475783  2.2503504   2.19684391
   5.52372844  0.99105583  0.35331134  8.06284788]
 [ 5.93379022  4.32891915  9.36334195  1.12451658 53.99631305  0.41194171
   6.12160287  7.57222004  4.58334177  4.88556574]
 [ 3.53018028  4.23464548  2.67646584  3.9667374   3.39451061 52.43434168
   3.93613733  4.48497298  8.67171225  9.11018089]
 [ 8.12642233  6.87609533  4.76160809  4.24902142  1.10302522  5.53749496
  46.42532501  2.37163584  5.98646926  1.60241653]
 [ 2.40225196  2.29340923  2.39529214  5.73122348  4.84349777  1.1536927
   9.76313459 35.36567204  0.89531

In [32]:
testRandMatrix(4)

Тест для матрицы
 [[0.05119408 0.07810772 0.40473775 0.00208086]
 [0.07810772 0.1288666  0.63250853 0.5685149 ]
 [0.40473775 0.63250853 0.02170422 0.25686087]
 [0.00208086 0.5685149  0.25686087 0.04319524]] и столбца [0.27119105 0.11753824 0.36222788 0.82812178]
Результат выполнения метода zeidelMethod:


/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/usr/lib/python3/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/lib/python3/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.27119105 0.11753824 0.36222788 0.82812178]

Результат выполнения метода zeidelMethodRelax:
Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.27119105 0.11753824 0.36222788 0.82812178]

Результат выполнения метода gaussMethod:
[-0.7549822518118776, 1.2650440915236492, 0.5242810706748791, -0.5595737087517612]. Погрешность не больше 0.01

Результат выполнения метода jacobiMethod:
Iterations =  2
[-0.75498225  1.26504409  0.52428107 -0.55957371]. Погрешность не больше 0.01



In [33]:
testHilbertMatrix(5)

Тест для матрицы
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] и столбца [0.13426633 0.0094724  0.66347949 0.77616444 0.81184857]
Результат выполнения метода zeidelMethod:
Iterations =  200000
[121.98388305248284, -1900.2195819882286, 7382.350673543126, -10472.705755180657, 4928.265272098724]. Погрешность не больше 0.01

Результат выполнения метода zeidelMethodRelax:
Iterations =  96523
[122.00278467597941, -1900.5665597098418, 7383.828931725489, -10474.918950879917, 4929.340943271085]. Погрешность не больше 0.01

Результат выполнения метода gaussMethod:
[122.00278882991957, -1900.5666319072268, 7383.829228421069, -10474.919383729683, 4929.341149566703]. Погрешность не больше 0.01

Результат выполнения метода jacobiMethod:
Iterations =  2
[   1