In [4]:
%run Zeidel.ipynb
%run Gauss.ipynb

In [5]:
def _format_matrix(min, max, size):
    return np.array((max - min) * np.random.random((size, size)) + min, dtype=np.float64)
    
def rand_matrix(size):
    A = np.array(np.random.rand(size, size), dtype=np.float64)
    A = np.tril(A) + np.tril(A, -1).T
    return A.T * A

def diag_matrix(size):
    A = _format_matrix(0.0, 10.0, size)
    for i in range(size):
        A[i, i] = sum(A[i]) + 1
    return A

def hilbert_matrix(size):
    ans = np.array(np.zeros((size, size)), dtype=np.float64)
    for i in range(size):
        for j in range(size):
            ans[i, j] = 1.0 / (i + j + 1)
    return ans

def gen_right_column(size):
    return np.array(np.random.random(size), dtype=np.float64)

In [6]:
def equalVector(a, b, eps):
    return math.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])) < eps

In [7]:
def _test(method, matrix, column):
    return method(matrix, column)

def _check_eps(a, b, eps):
    return abs(a - b) < eps
EPSILON = 1e-2
def _check_ans(matrix, column, res, size):
    eps = EPSILON
    c = np.matmul(matrix, res)
    for i in range(size):
        if not _check_eps(c[i], column[i], eps):
            return False
    return True

def _testAll(matrix_gen, size, methods):
    matrix, column = matrix_gen(size), gen_right_column(size)
    print(f'Тест для матрицы {matrix} и столбца {column}')
    for method in methods:
        print(f'Результат выполнения метода {method.__name__}:')
        res = _test(method, matrix, column)
        check = _check_ans(matrix, column, res, size)
        if check:
            print(f'{res}. Погрешность не больше {EPSILON}\n')
        else:
            print(f'разошлось: matrix * res = {np.matmul(matrix, res)}\n ожидаемый столбец = {column}\n')

def _get_methods():
    return [zeidelMethod, zeidelMethodRelax, gaussMethod]

def testDiagMatrix(size):
    _testAll(diag_matrix, size, _get_methods())

def testHilbertMatrix(size):
    _testAll(hilbert_matrix, size, _get_methods())
    
def testRandMatrix(size):
    _testAll(rand_matrix, size, _get_methods())

In [8]:
testDiagMatrix(10)

Тест для матрицы [[4.42175820e+01 3.85033460e+00 8.15886472e+00 7.29537110e+00
  8.83587781e+00 3.04012107e+00 4.85663154e+00 1.76793917e+00
  9.44364185e-01 7.96200517e-01]
 [6.22682523e+00 5.23578805e+01 3.82453442e+00 9.26559691e+00
  6.50458273e+00 4.17245412e+00 1.68138769e-01 2.84036006e+00
  5.28125943e+00 7.53349731e+00]
 [9.63449755e+00 1.76702373e+00 5.05389104e+01 3.14398287e+00
  8.41621098e+00 3.14927289e+00 4.69620458e+00 2.25771748e+00
  7.42802824e+00 6.11479002e+00]
 [8.59751503e+00 4.48831121e+00 4.54010856e+00 6.63047259e+01
  4.68202083e+00 7.72668803e+00 9.96431140e+00 9.86427481e+00
  1.41937616e+00 8.40793580e+00]
 [8.73923066e+00 9.63493032e+00 1.30805542e+00 9.00056947e+00
  5.74814644e+01 8.26228697e+00 8.87934749e-01 5.74500221e+00
  8.73872207e+00 3.14003869e+00]
 [4.43297498e+00 9.38790327e+00 4.31962293e+00 9.63841702e+00
  1.16358665e+00 5.97203230e+01 2.09321165e+00 4.30398111e+00
  9.88189481e+00 7.84883006e+00]
 [2.38666323e-01 1.88613546e+00 2.6202319

In [9]:
testRandMatrix(4)

Тест для матрицы [[0.29620194 0.15264037 0.40030824 0.0974049 ]
 [0.15264037 0.4996066  0.23790716 0.04201389]
 [0.40030824 0.23790716 0.50390019 0.58426897]
 [0.0974049  0.04201389 0.58426897 0.27197405]] и столбца [0.72196041 0.86829535 0.81784894 0.51518736]
Результат выполнения метода zeidelMethod:


/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.72196041 0.86829535 0.81784894 0.51518736]

Результат выполнения метода zeidelMethodRelax:


/home/anka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in double_scalars
  


Iterations =  200000
разошлось: matrix * res = [nan nan nan nan]
 ожидаемый столбец = [0.72196041 0.86829535 0.81784894 0.51518736]

Результат выполнения метода gaussMethod:
[0.8698191805633906, 1.1100310969678977, 0.8239341073936276, -0.3587589947150106]. Погрешность не больше 0.01



In [10]:
testHilbertMatrix(5)

Тест для матрицы [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]] и столбца [0.24864113 0.0599034  0.98059431 0.52600778 0.61340869]
Результат выполнения метода zeidelMethod:
Iterations =  200000
[667.7726812428098, -11907.708577626658, 49879.83664872733, -73882.2722872519, 35651.43049323902]. Погрешность не больше 0.01

Результат выполнения метода zeidelMethodRelax:
Iterations =  107856
[667.9056162748386, -11910.148845894999, 49890.23306184687, -73897.83735961607, 35658.995502139216]. Погрешность не больше 0.01

Результат выполнения метода gaussMethod:
[667.9056204298271, -11910.148918113104, 49890.23335863421, -73897.83779260666, 35658.99570850449]. Погрешность не больше 0.01

